# Generated by Django 6.0.4 on 2026-04-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationsession',
            options={'ordering': ('-updated_at',), 'permissions': [('can_view_all_consultations', 'Может просматривать все обращения'), ('can_assign_consultation', 'Может назначать обращения исполнителю'), ('can_change_consultation_status', 'Может изменять статус обращения'), ('can_mark_needs_specialist', 'Может помечать обращение как требующее специалиста'), ('can_close_consultation', 'Может закрывать обращения'), ('can_review_llm_logs', 'Может просматривать журналы взаимодействий с LLM')], 'verbose_name': 'Сеанс консультации', 'verbose_name_plural': 'Сеансы консультаций'},
        ),
    ]
