# Generated by Django 6.0.4 on 2026-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultationsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsession',
            name='awaiting_clarification',
            field=models.BooleanField(default=False, verbose_name='Ожидается уточнение'),
        ),
        migrations.AddField(
            model_name='consultationsession',
            name='last_analysis_category',
            field=models.CharField(blank=True, choices=[('family', 'Семейное право'), ('labor', 'Трудовое право'), ('housing', 'Жилищное право'), ('consumer', 'Защита прав потребителей'), ('inheritance', 'Наследственное право'), ('administrative', 'Административные вопросы'), ('civil', 'Гражданские вопросы'), ('other', 'Иное')], max_length=32, verbose_name='Последняя определённая категория'),
        ),
        migrations.AddField(
            model_name='consultationsession',
            name='last_analysis_scenario',
            field=models.CharField(blank=True, choices=[('typical_answer', 'Типовой ответ'), ('needs_clarification', 'Требуется уточнение'), ('needs_specialist', 'Передача специалисту'), ('out_of_scope', 'Вне рамок консультации'), ('insufficient_confidence', 'Недостаточная уверенность')], max_length=32, verbose_name='Последний сценарий анализа'),
        ),
    ]
