# Generated by Django 6.0.4 on 2026-04-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_role',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__in': ('Пользователь', 'Специалист поддержки', 'Юрист-консультант', 'Руководитель юридического отдела', 'Системный администратор')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_user_profiles', to='auth.group', verbose_name='Основная роль'),
        ),
    ]
