# Generated by Django 6.0.4 on 2026-05-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0003_consultationsession_awaiting_clarification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uid', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Идентификатор источника')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('document_type', models.CharField(blank=True, max_length=255, verbose_name='Тип документа')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='Издатель')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Статус')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('classifier', models.TextField(blank=True, verbose_name='Классификатор')),
                ('raw_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('source_name', models.CharField(default='RusLawOD', max_length=100, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LegalFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_type', models.CharField(default='plain_text', max_length=50, verbose_name='Тип фрагмента')),
                ('fragment_order', models.PositiveIntegerField(default=0, verbose_name='Порядок фрагмента')),
                ('article_number', models.CharField(blank=True, max_length=100, verbose_name='Номер статьи')),
                ('heading', models.CharField(blank=True, max_length=500, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category_hint', models.CharField(blank=True, max_length=255, verbose_name='Подсказка категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='knowledge.legaldocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Фрагмент нормативного документа',
                'verbose_name_plural': 'Фрагменты нормативных документов',
                'ordering': ('document_id', 'fragment_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConsultationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1, verbose_name='Ранг')),
                ('score', models.FloatField(default=0, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('request_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_sources_as_request', to='consultation.chatmessage', verbose_name='Сообщение-запрос')),
                ('response_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_sources_as_response', to='consultation.chatmessage', verbose_name='Сообщение-ответ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_sources', to='consultation.consultationsession', verbose_name='Сеанс консультации')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sources', to='knowledge.legalfragment', verbose_name='Фрагмент')),
            ],
            options={
                'verbose_name': 'Источник консультации',
                'verbose_name_plural': 'Источники консультаций',
                'ordering': ('session_id', 'rank', 'id'),
            },
        ),
    ]
